# Generated by Django 3.1 on 2020-08-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='gender',
        ),
        migrations.AddField(
            model_name='policy',
            name='desc',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
