# Generated by Django 3.1 on 2020-08-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200808_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='None', max_length=1),
        ),
        migrations.AddField(
            model_name='feedback',
            name='location',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='age',
            field=models.IntegerField(default='None'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='happy',
            field=models.BooleanField(default='None'),
        ),
    ]
