# Generated by Django 3.1 on 2020-08-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200808_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='happy',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='answer',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[('3', '3'), ('2', '3'), ('1', '1')], default='None', max_length=2),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='location',
            field=models.CharField(choices=[('Andhra', 'Andhra'), ('Telangana', 'Telangana'), ('West Bengal', 'West Bengal'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Goa', 'Goa'), ('Chattisghar', 'Chattisghar'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('J & K', 'J & K'), ('Jharkhand', 'Jharkhand'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Kerala', 'Kerala')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='policy',
            field=models.CharField(max_length=120),
        ),
    ]
