# Generated by Django 3.1 on 2020-08-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200808_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='region',
            field=models.CharField(choices=[('Andhra', 'Andhra'), ('Telanagana', 'Telanagana'), ('West Bengal', 'West Bengal'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Goa', 'Goa'), ('Chattisghar', 'Chattisghar'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('J & K', 'J & K'), ('Jharkhand', 'Jharkhand'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Kerala', 'Kerala')], default='Telangana', max_length=30),
        ),
    ]
